In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df.bedrooms.median()

4.0

In [10]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
df1 = df.drop('price', axis=1)
df1

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [12]:
from sklearn import linear_model

In [13]:
model = linear_model.LinearRegression()

In [14]:
model.fit(df1,df.price)

LinearRegression()

In [15]:
model.predict([[3000,3,40]])

C:\Users\Arayan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [16]:
model.predict([[2500,4,5]])

C:\Users\Arayan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [17]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
model.intercept_

221323.00186540384

In [22]:
3000*112.06244194+3*23388.88007794+40*-3231.71790863+221323.00186540384

498408.25157402386

In [23]:
2500*112.06244194+4*23388.88007794+5*-3231.71790863+221323.00186540384

578876.0374840139

In [30]:
model.score(df1,df.price)*100

95.50196399325819

## Exercise

In [124]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [148]:
hiring = pd.read_csv('hiring.csv')
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [149]:
!pip install word2number

In [150]:
hiring.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   experience                  6 non-null      object 
 1   test_score(out of 10)       7 non-null      float64
 2   interview_score(out of 10)  8 non-null      int64  
 3   salary($)                   8 non-null      int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 384.0+ bytes


In [151]:
from word2number import w2n

In [152]:
hiring.experience = hiring.experience.fillna('zero')

In [153]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [154]:
hiring.experience = hiring.experience.apply(w2n.word_to_num)

In [155]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [156]:
mean = hiring['test_score(out of 10)'].median()
mean

8.0

In [157]:
import math

In [159]:
mean1 = math.floor(hiring['test_score(out of 10)'].mean())
mean1

7

In [160]:
hiring['test_score(out of 10)'] = hiring['test_score(out of 10)'].fillna(mean1)

In [161]:
hiring

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [162]:
model = linear_model.LinearRegression()

In [163]:
model.fit(hiring[['experience','test_score(out of 10)','interview_score(out of 10)']],hiring['salary($)'])

LinearRegression()

In [164]:
model.predict([[2,9,6]])

C:\Users\Arayan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [165]:
model.predict([[12,10,10]])

C:\Users\Arayan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [166]:
model.score(hiring[['experience','test_score(out of 10)','interview_score(out of 10)']],hiring['salary($)'])

0.977013901427314